[package]
name = "anchor"
version = "0.1.0"
description = ""
repository = "https://github.com/project-serum/serum-dex"
edition = "2018"

[features]

derive = []
default = []

[dependencies]
thiserror = "1.0.20"
solana-sdk = { version = "1.3.14", default-features = false, features = ["program"] }
serum-common = { path = "../common" }
anchor-derive = { path = "./derive" }
anchor-attributes-program = { path = "./attributes/program" }
anchor-attributes-access-control = { path = "./attributes/access-control" }
borsh = { git = "https://github.com/project-serum/borsh", branch = "serum", features = ["serum-program"] }
solana-client-gen = { path = "../solana-client-gen" }
