[package]
name = "anchor-lang"
version = "0.0.0-alpha.0"
description = ""
repository = "https://github.com/project-serum/serum-dex"
edition = "2018"

[features]
derive = []
default = []

[dependencies]
thiserror = "1.0.20"
solana-program = "1.4.3"
solana-sdk = { version = "1.3.14", default-features = false, features = ["program"] }
anchor-derive-accounts = { path = "./derive/accounts", version = "0.0.0-alpha.0" }
anchor-attribute-program = { path = "./attribute/program", version = "0.0.0-alpha.0" }
anchor-attribute-access-control = { path = "./attribute/access-control", version = "0.0.0-alpha.0" }
anchor-attribute-account = { path = "./attribute/account", version = "0.0.0-alpha.0" }
serum-borsh = { version = "0.7.2+serum.2", features = ["serum-program"] }

[workspace]
members = [
    "cli",
    "syn",
    "attribute/*",
    "derive/*",
]
