[package]
name = "basic-program-0"
version = "0.1.0"
description = "A minimal example of an anchor program"
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "basic_program_0"

[dependencies]
borsh = { git = "https://github.com/project-serum/borsh", branch = "serum", features = ["serum-program"] }
solana-program = "1.4.3"
solana-sdk = { version = "1.3.14", default-features = false, features = ["program"] }
anchor = { path = "../../../../", features = ["derive"] }
