[package]
name = "anchor-cli"
version = "0.1.0"
authors = ["armaniferrante <armaniferrante@gmail.com>"]
edition = "2018"

[[bin]]
name = "anchor"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
anyhow = "1.0.32"
syn = { version = "1.0.54", features = ["full", "extra-traits"] }
anchor-syn = { path = "../syn" }
serde_json = "1.0"
shellexpand = "2.1.0"
