[package]
name = "basic-2"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "basic_2"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
serum-borsh = { version = "0.7.2+serum.2", features = ["serum-program"] }
solana-program = "1.4.3"
solana-sdk = { version = "1.3.14", default-features = false, features = ["program"] }
anchor-lang = { git = "https://github.com/project-serum/anchor", features = ["derive"] }
