[package]
name = "anchor-syn"
version = "0.27.0"
authors = ["Anchor Maintainers <accounts@200ms.io>"]
repository = "https://github.com/coral-xyz/anchor"
license = "Apache-2.0"
description = "Anchor syntax parsing and code generation tools"
rust-version = "1.60"
edition = "2021"

[features]
allow-missing-optionals = []
init-if-needed = []
idl = []
hash = []
default = []
anchor-debug = []
seeds = []
event-cpi = []

[dependencies]
anyhow = "1"
bs58 = "0.5"
heck = "0.3"
proc-macro2 = { version = "1", features=["span-locations"]}
quote = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
syn = { version = "1", features = ["full", "extra-traits", "parsing"] }
thiserror = "1"
